import type { Metadata } from "next";
import "../styles/globals.css";
import "antd/dist/reset.css";
import { AuthProvider } from "@/lib/auth/auth-context";
import { GoogleOAuthProvider } from "@react-oauth/google";


export const metadata: Metadata = {
  title: "Project Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const clientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <GoogleOAuthProvider clientId={clientId ? clientId : ""}>
            {children}
          </GoogleOAuthProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
