// import "antd/dist/reset.css";
import "@/styles/globals.css";
import "quill/dist/quill.snow.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import { ProjectProvider } from "@/context/ProjectContext";
export const metadata: Metadata = {
  title: "Project Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <ProjectProvider>
          <Providers>{children}</Providers>
        </ProjectProvider>
      </body>
    </html>
  );
}
