import "@/styles/globals.css";
import "quill/dist/quill.snow.css";
import "sweetalert2/dist/sweetalert2.min.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
export const metadata: Metadata = {
  title: "Project Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
